project:
  type: website
  output-dir: _site

website:
  title: "galaxias"
  twitter-card: true
  open-graph: true
  favicon: images/favicon_galaxias.ico
  search: false
  navbar:
    background: '#f0f0f0'
    foreground: '#222322'
    right:
      - text: R package
        href: https://galaxias.ala.org.au/R
      - text: Python package
        href: https://galaxias.ala.org.au/Python
      - href: https://www.ala.org.au
        icon: ala
  page-footer:
    border: false
    left: |
      [![](images/ALA_Logo.jpg){fig-alt="Atlas of Living Australia" width=200px}](https://ala.org.au/)
    center:
      - text: Copyright
        href: https://www.ala.org.au/terms-of-use/#cy
      - text: License
        href: https://creativecommons.org/licenses/by/3.0/au/
      - text: Terms of Use
        href: https://www.ala.org.au/terms-of-use/
      - text: Support
        href: https://ala.org.au/contact-us/
    right:
      - icon: instagram
        href: https://instagram.com/atlaslivingaustralia
      - icon: facebook
        href: https://facebook.com/atlaslivingaustralia
      - icon: linkedin
        href: https://au.linkedin.com/company/atlas-of-living-australia

format:
  html:
    highlight-style: arrow
    code-block-border-left: "#6c9b4b"
    code-block-bg: true
    theme: cosmo
    css: styles.css



